# Site
repository: pramoddilipakumar.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: PRAMOD DILIPAKUMAR
title: DEVOPS ENGINEER
email: pramod.dilipakumar@gmail.com
website: https://www.medium.com/@pramod.dilipakumar

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username:
github_username: pramoddilipakumar
instagram_username:
linkedin_username: pramoddevops

# Additional icon links
additional_links:
  - title: personal blog
    icon: fas fa-globe
    url: https://www.medium.com/@pramod.dilipakumar
  # - title: another link
  #   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
  #   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Pramod, a seasoned DevOps Engineer with 4 years of hands-on experience. With a track record spanning over 5 years in the IT industry, I've honed my expertise in cloud technologies and DevOps practices. My dedication lies in harnessing cutting-edge tools and technologies to create scalable, efficient solutions that drive impactful outcomes.
  
  Technical Skills:
    - Cloud Platforms: AWS, Azure
    - Programming: Python, Bash, YAML
    - DevOps Tools: Git, Maven, SonarQube, Nexus, Jenkins, Terraform, Ansible, Docker, Kubernetes.
  
  Throughout my career, I've engaged in diverse projects that sharpened my technical acumen and fostered collaboration with cross-functional teams. Thriving in dynamic, fast-paced environments, I'm committed to staying ahead of the curve by keeping myself updated with the latest industry trends.
  
  As a certified Azure professional with extensive AWS hands-on experience, I take pride in architecting robust cloud infrastructures for seamless operations and high availability. My proficiency in DevOps tools empowers me to execute automated workflows and implement continuous integration/continuous deployment (CI/CD) pipelines, ensuring rapid and reliable software delivery.
  
  I believe in fostering a collaborative work environment and thrive on exchanging knowledge with my colleagues to collectively achieve success. I am always excited about exploring new opportunities to learn and grow.
  
  If you're looking for someone who is dedicated, innovative, and constantly driven to make a difference, let's connect! I am open to networking, collaboration, and discussing potential opportunities.

content:
  - title: Work Experience and Key Achievements # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        link: github.com/pramoddilipkumar
        # link_text: Project Website
        additional_links:
          - title: SIMS Java-based web application
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title: Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HAEGL Technologies Pvt Ltd.
        link: haegl.in
        sub_title: Devops Engineer
        caption: September 2019 - Present
        quote: >
          In the realm of DevOps, we sculpt technology into solutions that drive efficiency, amplify reliability, and foster a culture of constant evolution.
        description: | # this will include new lines to allow paragraphs
            - Led the design, architecture, and implementation of the ERP system, leveraging AWS services for scalability and reliability.
            - Managed Git repositories and branches to enforce version control best practices and facilitate collaborative development.
            - Achieved a 30% reduction in provisioning time and enhanced resource agility by implementing Infrastructure as Code using Terraform across AWS and Azure environments.
            - Automated system configuration through Ansible playbooks, resulting in a 40% decrease in manual intervention and improved overall reliability.
            - Orchestrated comprehensive CI/CD pipelines utilizing Jenkins, reducing deployment time by 30% for various applications across both AWS and Azure platforms.
            - Developed Python scripts to optimize operational efficiency by streamlining routine tasks in hybrid cloud workflows.
            - Seamlessly integrated SonarQube into software pipelines, elevating code quality analysis and maintainability for projects spanning AWS and Azure.
            - Managed the Nexus artifact repository effectively, ensuring seamless artifact storage and versioning to enhance collaboration in complex multi-cloud setups.
            - Designed Dockerfiles and Docker Compose configurations meticulously, ensuring consistent and reliable application deployment across AWS and Azure.
            - Leveraged stateful application components to efficiently manage critical data and ensure system-wide consistency, enhancing the stability of multi-cloud architectures.
            - Proficiently administered diverse databases, including MySQL, Amazon RDS, and DynamoDB, to uphold data integrity and efficient storage solutions across AWS and Azure.
            - Implemented serverless technologies like AWS Lambda and Azure Functions, creating scalable components within the cloud architecture.
            - Skillfully oversaw Kubernetes clusters (AWS EKS and Azure AKS), optimizing scalability and availability for microservices-based applications.
            - Orchestrated Kubernetes deployments using meticulous YAML manifests, ensuring smooth scaling and updates for containerized services across both AWS and Azure.
            - Monitored and maintained application health using CloudWatch, Prometheus, Grafana, Azure Monitor, and Application Insights, ensuring prompt anomaly detection and resolution.
            - Strategically aligned AWS and Azure services to optimize multi-cloud configurations, achieving a harmonious balance between cost-effectiveness and high-performance outcomes, significantly contributing to organizational success.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BVBCET, Hubli
        sub_title: Bachelor of Engineering
        quote: >
          Established in 1947 with a motto of Creating Value, Leveraging Knowledge. BVBCET is one of the oldest higher education institutions in India, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Beyond my devotion to DevOps engineering, I find joy in:
      - Reading novels and non-fictional books
      - Playing cricket (I fancy myself a deceptive bowler like Virat Kohli)
      - Engaging in movie debates
      - Enjoying a cup of tea, a delightful companion to reflection.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
